import { useCallback, useEffect, useState } from 'react'
import { NavLink, Navigate, Outlet, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import Button from '../src/atoms/Button.jsx'
import api, { apiMessage } from '../utils/veilleMarcheApi.js'

const NAV_ITEMS = [['/', 'Accueil', '⌂'], ['/nouveau-releve', 'Nouveau relevé', '＋'], ['/brouillons', 'Brouillons', '◫'], ['/historique', 'Historique', '◷'], ['/promotions', 'Promotions', '✦']]
const STEPS = ['visite', 'categorie', 'sous_categorie', 'sku', 'recap']
const EMPTY = { categorie: '', sous_categorie: '' }

function ModuleLayout({ onSignOut }) { return <div className="vm-shell"><aside className="vm-sidebar" aria-label="Navigation Veille Marché"><div className="vm-sidebar__brand"><img src="/image_enosisapp.png" alt="Enosis Group"/><div><strong>eOne</strong><span>Veille Marché</span></div></div><nav className="vm-sidebar__nav">{NAV_ITEMS.map(([to,label,icon]) => <NavLink key={to} to={`/veille-marche${to}`} end={to === '/'}><i aria-hidden="true">{icon}</i><span>{label}</span></NavLink>)}</nav><button className="vm-sidebar__logout" onClick={onSignOut}>Déconnexion</button></aside><main className="vm-main"><Outlet/></main></div> }
function PageHeader({ title, children }) { return <header className="page-header"><div><p className="eyebrow">VEILLE MARCHÉ</p><h1>{title}</h1></div>{children}</header> }
function Status({ value }) { const tone = ['Soumise','Active'].includes(value) ? 'success' : ['Brouillon','Planifiée'].includes(value) ? 'warning' : 'danger'; return <span className={`badge badge--${tone}`}>{value}</span> }
function Loader() { return <div className="loader" role="status"><span className="loader__dot"/>Chargement…</div> }
function EmptyState({ title, text }) { return <div className="empty-state"><div className="empty-state__icon">⌁</div><h2>{title}</h2><p>{text}</p></div> }
function formatDate(value) { return value ? new Date(value).toLocaleString('fr-MA', { dateStyle:'medium', timeStyle:'short' }) : '—' }

function Home() { const navigate = useNavigate(); return <><section className="home-intro"><p className="eyebrow">VEILLE MARCHÉ</p><h1>Votre centre de collecte</h1><p>Pilotez vos relevés terrain, retrouvez vos brouillons et suivez vos opérations commerciales depuis un espace unique.</p></section><section className="home-grid">{[['/nouveau-releve','Nouveau relevé','Démarrer une collecte terrain.'],['/brouillons','Brouillons','Reprendre un relevé sauvegardé.'],['/historique','Historique','Consulter les relevés soumis.'],['/promotions','Promotions','Explorer les opérations commerciales.']].map(([to,title,text]) => <button className="home-card" key={to} onClick={() => navigate(`/veille-marche${to}`)}><strong>{title}</strong><span>{text}</span><b>→</b></button>)}</section></> }
function VisitList({ statut, title, emptyTitle, emptyText }) { const [items,setItems] = useState([]), [loading,setLoading] = useState(true), [error,setError] = useState(''); const navigate = useNavigate(), location = useLocation(); useEffect(() => { api.visites(statut).then(setItems).catch((e) => setError(apiMessage(e))).finally(() => setLoading(false)) }, [statut]); return <><PageHeader title={title}/>{location.state?.successMessage && <div className="alert alert--success">{location.state.successMessage}</div>}{loading ? <Loader/> : error ? <div className="alert alert--error">{error}</div> : !items.length ? <EmptyState title={emptyTitle} text={emptyText}/> : <div className="table-card"><div className="table-scroll"><table className="data-table"><thead><tr><th>Date automatique</th><th>Magasin</th><th>Statut</th><th/></tr></thead><tbody>{items.map((visit) => <tr key={visit.id}><td>{formatDate(visit.created_at)}</td><td>{visit.magasin_nom || 'Point de vente'}</td><td><Status value={visit.statut === 'soumise' ? 'Soumise' : 'Brouillon'}/></td><td><Button size="sm" variant="secondary" onClick={() => navigate(statut === 'brouillon' ? `/veille-marche/nouveau-releve/${visit.id}` : `/veille-marche/historique/${visit.id}`)}>{statut === 'brouillon' ? 'Compléter' : 'Voir'}</Button></td></tr>)}</tbody></table></div></div>}</> }

function Wizard({ user }) {
  const { visitId } = useParams(); const navigate = useNavigate();
  const [step,setStep] = useState('visite'), [record,setRecord] = useState(null), [store,setStore] = useState(null), [form,setForm] = useState({secteur:'',ville:''}), [selection,setSelection] = useState(EMPTY), [options,setOptions] = useState({secteurs:[],villes:[],categories:[],sous:[],marques:[]}), [prices,setPrices] = useState({}), [completed,setCompleted] = useState([]), [loading,setLoading] = useState(true), [saving,setSaving] = useState(false), [error,setError] = useState(''), [transitioning,setTransitioning] = useState(false);
  const transition = useCallback((next) => { setTransitioning(true); window.setTimeout(() => { setStep(next); setTransitioning(false); }, 240) }, []);
  useEffect(() => { let alive = true; Promise.all([api.secteurs(),api.villes(),api.categories(),visitId ? api.visites().then((all) => all.find((visit) => visit.id === visitId)) : Promise.resolve(null),visitId ? api.releves(visitId) : Promise.resolve([])]).then(async ([secteurs,villes,categories,visit,releves]) => { if (!alive) return; setOptions((old) => ({...old,secteurs,villes,categories})); if (visit) { const magasin = await api.magasin(visit.magasin); if (!alive) return; setRecord(visit); setStore(magasin); setForm({secteur:magasin.secteur,ville:magasin.ville}); setSelection({categorie:visit.categorie || '',sous_categorie:visit.sous_categorie || ''}); setStep(STEPS.includes(visit.etape) ? visit.etape : 'visite'); } setPrices(Object.fromEntries(releves.map((row) => [row.sku,row]))); }).catch((e) => alive && setError(apiMessage(e))).finally(() => alive && setLoading(false)); return () => { alive = false } }, [visitId]);
  useEffect(() => { if (!selection.categorie) return; api.sousCategories(selection.categorie).then((sous) => setOptions((old) => ({...old,sous}))).catch((e) => setError(apiMessage(e))) }, [selection.categorie]);
  useEffect(() => { if (step !== 'sku' || !selection.sous_categorie) return; api.marques({ sous_categorie:selection.sous_categorie }).then(async (marques) => { const result = await Promise.all(marques.map(async (marque) => ({...marque,skus:await api.skus(marque.id)}))); setOptions((old) => ({...old,marques:result})); }).catch((e) => setError(apiMessage(e))) }, [step,selection.sous_categorie]);
  const createVisit = async () => { if (record) return transition('categorie'); if (!form.secteur || !form.ville) return setError('Sélectionnez un secteur et une ville.'); setSaving(true); try { const magasin = await api.createMagasin(form); const visit = await api.createVisite(magasin.id); setStore(magasin); setRecord(visit); transition('categorie'); } catch (e) { setError(apiMessage(e)); } finally { setSaving(false); } };
  const chooseCategory = async (categorie) => { if (!record) return; setSelection({categorie,sous_categorie:''}); setSaving(true); try { await api.updateVisite(record.id,{categorie,etape:'sous_categorie'}); transition('sous_categorie'); } catch (e) { setError(apiMessage(e)); } finally { setSaving(false); } };
  const chooseSousCategory = async (sous_categorie) => { if (!record) return; setSelection((old) => ({...old,sous_categorie})); setSaving(true); try { await api.updateVisite(record.id,{sous_categorie,segment:null,etape:'sku'}); transition('sku'); } catch (e) { setError(apiMessage(e)); } finally { setSaving(false); } };
  const next = async () => { if (step === 'visite') return createVisit(); if (step === 'categorie' && selection.categorie) return chooseCategory(selection.categorie); if (step === 'sous_categorie' && selection.sous_categorie) return chooseSousCategory(selection.sous_categorie); if (step === 'sku') { setSaving(true); try { await api.updateVisite(record.id,{etape:'recap'}); transition('recap'); } catch (e) { setError(apiMessage(e)); } finally { setSaving(false); } } };
  const back = () => { const index = STEPS.indexOf(step); if (index) setStep(STEPS[index - 1]) };
  const payload = () => Object.values(prices).filter((row) => row.prix_conso_ttc && row.prix_detail_ttc).map(({sku,prix_conso_ttc,prix_detail_ttc,promotion,commentaire,photo_url}) => ({sku,prix_conso_ttc,prix_detail_ttc,promotion,commentaire,photo_url}));
  const save = async (submit) => { if (!record) return; if (submit && !payload().length) return setError('Renseignez au moins un SKU et ses deux prix avant de soumettre.'); setSaving(true); try { await api.saveReleves(record.id,payload(),!submit); navigate(submit ? '/veille-marche/historique' : '/veille-marche/brouillons',{state:{successMessage:submit ? 'Relevé soumis avec succès.' : 'Brouillon sauvegardé avec succès.'}}); } catch (e) { setError(apiMessage(e)); } finally { setSaving(false); } };
  const nextCategory = async () => { if (!record || !store) return; setSaving(true); try { await api.saveReleves(record.id,payload(),false); const nextVisit = await api.createVisite(store.id); setCompleted((old) => [...old,selection.categorie]); setRecord(nextVisit); setSelection(EMPTY); setPrices({}); transition('categorie'); } catch (e) { setError(apiMessage(e)); } finally { setSaving(false); } };
  if (loading) return <Loader/>; const hasNextCategory = options.categories.some((item) => item.id !== selection.categorie && !completed.includes(item.id));
  return <><PageHeader title="Nouveau relevé"/>{error && <div className="alert alert--error">{error}</div>}<section className={`wizard-card ${transitioning ? 'is-transitioning' : ''}`}><WizardProgress current={step}/><div className="wizard-body">{step === 'visite' && <VisitStep form={form} options={options} onChange={(field,value) => setForm((old) => ({...old,[field]:value}))} onReady={createVisit}/>} {step === 'categorie' && <SelectionCards items={options.categories} value={selection.categorie} onSelect={chooseCategory} icon="◈"/>} {step === 'sous_categorie' && <SelectionCards items={options.sous} value={selection.sous_categorie} onSelect={chooseSousCategory} icon="◇"/>} {step === 'sku' && <SkuFields brands={options.marques} prices={prices} setPrices={setPrices}/>} {step === 'recap' && <Recap form={form} selection={selection} options={options} prices={prices} record={record} store={store} user={user}/>}</div>{step === 'recap' ? <div className="wizard-actions wizard-actions--recap"><Button variant="secondary" onClick={back} disabled={saving}>Retour</Button><Button variant="secondary" onClick={() => save(false)} disabled={saving}>Sauvegarder le brouillon</Button><Button onClick={() => save(true)} disabled={saving}>Soumettre</Button>{hasNextCategory && <Button variant="secondary" onClick={nextCategory} disabled={saving}>Passer à la catégorie suivante</Button>}</div> : <div className="wizard-actions"><Button variant="secondary" onClick={back} disabled={saving} style={{visibility:step === 'visite' ? 'hidden' : 'visible'}}>Retour</Button><Button onClick={next} disabled={saving}>{saving ? 'Enregistrement…' : 'Continuer'}</Button></div>}</section></>
}
function WizardProgress({ current }) { const index = STEPS.indexOf(current); const labels = ['Visite','Catégorie','Sous-catégorie','Prix / SKU','Récapitulatif']; return <ol className="wizard-progress">{STEPS.map((name,i) => <li key={name} className={i <= index ? (i === index ? 'is-current' : 'is-complete') : ''}><span>{i + 1}</span><small>{labels[i]}</small></li>)}</ol> }
function VisitStep({ form, options, onChange, onReady }) { return <div className="visit-step"><div className="step-heading"><span className="step-heading__icon">⌖</span><div><h2>Où effectuez-vous le relevé ?</h2><p>La visite est créée dès que le secteur et la ville sont choisis.</p></div></div><div className="selection-grid"><SelectCard label="Secteur" value={form.secteur} items={options.secteurs} onChange={(value) => onChange('secteur',value)}/><SelectCard label="Ville" value={form.ville} items={options.villes} onChange={(value) => { onChange('ville',value); if (form.secteur) window.setTimeout(onReady,250) }}/></div></div> }
function SelectCard({ label,value,items,onChange }) { return <label className="select-card"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}><option value="">Choisir {label.toLowerCase()}</option>{items.map((item) => <option key={item.id} value={item.id}>{item.nom}</option>)}</select></label> }
function SelectionCards({ items,value,onSelect,icon }) { return <div className="selection-cards">{items.map((item) => <button type="button" className={`selection-card ${value === item.id ? 'is-selected' : ''}`} key={item.id} onClick={() => onSelect(item.id)}><i>{icon}</i><strong>{item.nom}</strong><span>Choisir et continuer</span><b>→</b></button>)}</div> }
function SkuFields({ brands, prices, setPrices }) {
  if (!brands.length) return <div className="skeleton-list"><span/><span/><span/></div>
  const toggle = (sku, value, checked) => checked
    ? setPrices((current) => ({ ...current, [sku.id]: value }))
    : setPrices((current) => Object.fromEntries(Object.entries(current).filter(([id]) => id !== sku.id)))
  return <div>{brands.map((brand) => <section className="sku-block" key={brand.id}><header><div><h2>{brand.nom}</h2><p>{brand.skus.length} SKU disponibles</p></div>{brand.concurrent && <Status value="Concurrent"/>}</header>{brand.skus.map((sku) => { const value = prices[sku.id] || {sku:sku.id,sku_nom:sku.nom,marque_nom:brand.nom,prix_conso_ttc:'',prix_detail_ttc:'',promotion:'',commentaire:'',photo_url:''}; const change = (key,val) => setPrices((current) => ({...current,[sku.id]:{...value,[key]:val}})); return <article className="sku-row sku-row--expanded" key={sku.id}><label className="sku-select"><input type="checkbox" checked={Boolean(prices[sku.id])} onChange={(event) => toggle(sku,value,event.target.checked)}/><strong>{sku.nom}</strong></label>{prices[sku.id] && <><input type="number" min="0" step="0.01" placeholder="Prix conso TTC" value={value.prix_conso_ttc} onChange={(e) => change('prix_conso_ttc',e.target.value)}/><input type="number" min="0" step="0.01" placeholder="Prix détail TTC" value={value.prix_detail_ttc} onChange={(e) => change('prix_detail_ttc',e.target.value)}/><input placeholder="Promotion" value={value.promotion} onChange={(e) => change('promotion',e.target.value)}/><input placeholder="URL photo" value={value.photo_url} onChange={(e) => change('photo_url',e.target.value)}/><input placeholder="Commentaire" value={value.commentaire} onChange={(e) => change('commentaire',e.target.value)}/></>}</article>})}</section>)}</div>
}
function Recap({ form,selection,options,prices,record,store,user }) { const name = (items,id) => items.find((item) => item.id === id)?.nom || '—'; const rows = Object.values(prices), userName = [user?.first_name,user?.last_name].filter(Boolean).join(' ') || user?.email || 'Utilisateur connecté'; const completed = rows.filter((row) => row.prix_conso_ttc && row.prix_detail_ttc).length; return <div className="recap-dashboard"><header className="recap-hero"><div><p className="eyebrow">VALIDATION FINALE</p><h2>Votre relevé est prêt à être vérifié.</h2><p>Contrôlez les informations avant de l’enregistrer ou de le soumettre définitivement.</p></div><Status value={record?.statut === 'soumise' ? 'Soumise' : 'Brouillon'}/></header><section className="recap-section"><h3>Informations générales</h3><div className="recap-grid"><Summary label="Date du relevé" value={formatDate(record?.date_visite)}/><Summary label="Date de création" value={formatDate(record?.created_at)}/><Summary label="Dernière modification" value={formatDate(record?.updated_at)}/><Summary label="Utilisateur connecté" value={userName}/><Summary label="Statut" value={record?.statut === 'soumise' ? 'Soumise' : 'Brouillon'}/></div></section><section className="recap-section"><h3>Informations magasin</h3><div className="recap-grid"><Summary label="Secteur" value={name(options.secteurs,form.secteur)}/><Summary label="Ville" value={name(options.villes,form.ville)}/><Summary label="Magasin" value={store?.nom || record?.magasin_nom || 'Point de vente'}/><Summary label="Adresse" value={store?.adresse_nom || store?.adresse || 'Non renseignée'}/><Summary label="Catégorie" value={name(options.categories,selection.categorie)}/><Summary label="Sous-catégorie" value={name(options.sous,selection.sous_categorie)}/></div></section><section className="recap-stats"><div><span>SKU sélectionnés</span><strong>{rows.length}</strong></div><div><span>Prix complets</span><strong>{completed}</strong></div><div><span>Promotions</span><strong>{rows.filter((row) => row.promotion).length}</strong></div><div><span>Photos</span><strong>{rows.filter((row) => row.photo_url).length}</strong></div></section><section className="recap-section"><h3>Informations produits</h3><div className="table-card recap-table"><div className="table-scroll"><table className="data-table"><thead><tr><th>Marque</th><th>SKU</th><th>Prix conso</th><th>Prix détail</th><th>Promotion</th><th>Photo</th><th>Commentaire</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.sku}><td>{row.marque_nom || '—'}</td><td>{row.sku_nom || row.sku}</td><td>{row.prix_conso_ttc || '—'}</td><td>{row.prix_detail_ttc || '—'}</td><td>{row.promotion || '—'}</td><td>{row.photo_url ? <a href={row.photo_url} target="_blank" rel="noreferrer">Voir</a> : '—'}</td><td>{row.commentaire || '—'}</td></tr>) : <tr><td colSpan="7">Aucun SKU sélectionné.</td></tr>}</tbody></table></div></div></section></div> }
function Summary({ label,value }) { return <p><span>{label}</span>{value}</p> }
function Detail() { const {visitId} = useParams(); const [items,setItems] = useState([]); const navigate = useNavigate(); useEffect(() => { api.releves(visitId).then(setItems) },[visitId]); return <><PageHeader title="Détail du relevé"><Button variant="secondary" onClick={() => navigate('/veille-marche/historique')}>Retour</Button></PageHeader><div className="table-card"><table className="data-table"><thead><tr><th>Marque</th><th>SKU</th><th>Prix conso TTC</th><th>Prix détail TTC</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.marque_nom}</td><td>{item.sku_nom}</td><td>{item.prix_conso_ttc}</td><td>{item.prix_detail_ttc}</td></tr>)}</tbody></table></div></> }
function Promotions() { const promotions = [{name:'Offre rentrée MIO',status:'Active',period:'01/09 — 30/09',discount:'15%',category:'Détergent',brand:'MIO',sku:'500gr, 1Kg'},{name:'Prix spécial Papillon',status:'Planifiée',period:'15/08 — 15/09',discount:'10%',category:'Paper',brand:'Papillon',sku:'4, 12'},{name:'Pack Clean Up',status:'Terminée',period:'01/07 — 31/07',discount:'12%',category:'Paper',brand:'Clean Up',sku:'6 compact'}]; return <><PageHeader title="Promotions"/><div className="kpi-grid"><div><span>Promotions</span><strong>3</strong></div><div><span>Actives</span><strong>1</strong></div><div><span>Réduction moyenne</span><strong>12%</strong></div></div><div className="promotion-grid">{promotions.map((item) => <article key={item.name} className="promotion-card"><Status value={item.status}/><h2>{item.name}</h2><p>{item.period} · {item.discount}</p><dl><dt>Catégorie</dt><dd>{item.category}</dd><dt>Marque</dt><dd>{item.brand}</dd><dt>SKU</dt><dd>{item.sku}</dd></dl></article>)}</div></> }
export default function VeilleMarcheModule({onSignOut,session}) { return <Routes><Route path="/veille-marche" element={<ModuleLayout onSignOut={onSignOut}/> }><Route index element={<Home/>}/><Route path="nouveau-releve" element={<Wizard user={session?.user}/>}/><Route path="nouveau-releve/:visitId" element={<Wizard user={session?.user}/>}/><Route path="brouillons" element={<VisitList statut="brouillon" title="Brouillons" emptyTitle="Aucun brouillon" emptyText="Vos relevés sauvegardés apparaîtront ici."/>}/><Route path="historique" element={<VisitList statut="soumise" title="Historique" emptyTitle="Aucun relevé soumis" emptyText="Les relevés soumis apparaîtront ici en lecture seule."/>}/><Route path="historique/:visitId" element={<Detail/>}/><Route path="promotions" element={<Promotions/>}/></Route><Route path="*" element={<Navigate to="/veille-marche" replace/>}/></Routes> }
